### ISSUE TITLE
Some Jinja2 environment globals not working

### ISSUE THREAD

**Issue by mootoom** [aio-libs/aiohttp-jinja2#194]
Hello AIO team.

Firstly, thank you for an awesome piece of software. Really amazing work.

I am however having an issue with the live reloading of the jinja2 templates which we are populating dynamically from a DB and via REST calls to other microservices. The templates do not update with the new data even though we have disabled caching on the jinja2 environment as well as enabled auto reloading:

```
aiohttp_jinja2.setup(
        app,
        loader=jinja2.FileSystemLoader(str(THIS_DIR / 'templates')),
        auto_reload=True,
        cache_size=0
    )
```
We have tried lots of combinations of key word arguments but the above should be correct and it does not work. Any help in this regard would be greatly appreciated.

aiohttp (3.0.7)
aiohttp-debugtoolbar (0.5.0)
aiohttp-devtools (0.8)
aiohttp-jinja2 (0.17.0)
async-timeout (2.0.0)
attrs (17.4.0)
chardet (3.0.4)
click (6.7)
idna (2.6)
idna-ssl (1.0.1)
isort (4.3.4)
Jinja2 (2.10)
MarkupSafe (1.0)
multidict (4.1.0)
pip (9.0.1)
PyYAML (3.12)
setuptools (38.5.2)
watchgod (0.0.3)
wheel (0.30.0)
yarl (1.1.1)

**Comment by asvetlov** [comment]
Sorry, aiohttp-jinja2 does nothing special for auto-reloading.
If you'll find that the library should be "fixed" somehow to support reload -- please make a PR.

I'm closing the issue since direct autoreload support is out of aiohttp-jinja2 scope, it should be solved by external tool.

P.S.
If you are populating templates from DB -- you should use custom database loader perhaps, FileSystemLoader is dedicated to file templates explicitly. I don't know loaders internals good enough to provide more info, custom loaders are not belong to aiohttp-jinja2 domain.
