### ISSUE TITLE
Documentation on ReadTheDocs is outdated

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/aiohttp-jinja2#251]
I tried to find some info about autoescaping and it is not available in both stable and latest docs builds.
(available in sources).
That is why I guess that current docs stable is of 0.13.0 release or earlier

**Comment by asvetlov** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by asvetlov** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @asvetlov.

**Comment by asvetlov** [comment]
The doc mentions autoescape now
